indent_style = "Block"
reorder_imports = true
max_width = 100
quote_style = "Double"
wrap_comments = true
fn_single_line = true
struct_field_align_threshold = 20
brace_style = "SameLineWhere"
hard_tabs = false
no_semi = false
wrap_newline_at = 80
format_code_in_doc_comments = true
empty_item_single_line = true
normalize_comments = true
group_imports = "StdExternalCrate"
comment_width = 80
trailing_comma = "Always"
chain_width = 160
use_small_heuristics = "Max"
unstable_features = true
match_arm_blocks = false
where_single_line = true
struct_lit_single_line = true
enum_discrim_align_threshold = 20
fn_empty_single_line=true
struct_trailing_comma = "Always"
struct_lit_trailing_comma = "Always"
enum_trailing_comma = true
where_trailing_comma = true
match_block_trailing_comma = true
match_wildcard_trailing_comma = true